questions_answers.settings:
  type: config_object
  label: 'Entity Questions and Answers settings'
  mapping:
    terms_and_conditions:
      type: string
      label: 'Path to direct users to a terms and conditions for the module'
    no_access_message:
      type: string
      label: 'Message displayed to users with no access to ask questions'
