# Schema for the configuration files of the Mobile Number module.

# Storage schema.
field.storage_settings.mobile_number:
  type: mapping
  label: Storage settings
  mapping:
    unique:
      type: integer
      label: Uniqueness

field.field_settings.mobile_number:
  type: mapping
  label: Field settings
  mapping:
    verify:
      type: string
      label: Verification
    countries:
      type: sequence
      label: Allowed Countries
    message:
     type: string
     label: Verification message

field.widget.settings.mobile_number_default:
  type: mapping
  label: Widget settings
  mapping:
    countries:
      type: sequence
      label: Allowed Countries
    default_country:
     type: string
     label: Default Country
    placeholder:
     type: string
     label: Placeholder

mobile_number.settings:
  type: config_object
  label: 'Mobile Number settings'
  mapping:
    tfa_field:
      type: string
      label: 'TFA User Field'
    verification_secret:
      label: 'Verification Secrete'
      type: string
